name: Windows build

on: [push]

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: 'true'

    - name: Install Qt
      uses: jurplel/install-qt-action@v2
      with:
        version: '6.1.2'
        dir: '${{github.workspace}}/qt/'

    - name: Configure build
      working-directory: ${{github.workspace}}
      # CMAKE_BUILD_TYPE is redundant for msvc, but keep it in case we switch
      # generators.
      run: cmake -B ${{github.workspace}}/build -D CMAKE_BUILD_TYPE=$env:BUILD_TYPE

    - name: Build
      working-directory: ${{github.workspace}}/build
      run: cmake --build . --config $env:BUILD_TYPE

    # Copy Qt dlls into dir with bianries.
    - name: windeployqt
      run: windeployqt.exe ${{github.workspace}}/build/${{env.BUILD_TYPE}}

    - name: Archive build
      uses: actions/upload-artifact@v2
      with:
        name: win-${{env.BUILD_TYPE}}
        path: ${{github.workspace}}/build/${{env.BUILD_TYPE}}
