name: Linux build

on: [push]

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: 'true'

    - name: Install Qt
      uses: jurplel/install-qt-action@v2
      with:
        version: '6.1.2'
        dir: '${{github.workspace}}/qt/'

    - name: Configure build
      working-directory: ${{github.workspace}}
      run: cmake -B ${{github.workspace}}/build -D CMAKE_BUILD_TYPE=$BUILD_TYPE

    - name: Build
      working-directory: ${{github.workspace}}/build
      run: cmake --build . --config $BUILD_TYPE

    # Work around for https://github.com/actions/upload-artifact/issues/38
    # dropping permissions.
    - name: tar files
      working-directory: ${{github.workspace}}/build
      run: tar -cvf mp4-manipulator.tar mp4-manipulator

    - name: Archive build
      uses: actions/upload-artifact@v2
      with:
        name: linux-${{env.BUILD_TYPE}}
        path: ${{github.workspace}}/build/mp4-manipulator.tar
